### ISSUE TITLE
Suggestion for topic

### ISSUE THREAD

**Issue by TotallyInformation** [karstenj/node-red-contrib-fsm#1]
Hi, liking your FSM node but wouldn't it be better if the topic used more standard MQTT type separators so that you had `FSM_1/transition` instead of `FSM_1_transition`?

That would make it much easier to pass the output to MQTT and be able to subscribe to all messages related to a specific fsm.

**Comment by karstenj** [comment]
Hi Julian, 

see my previous post.

Regards
Karsten
